### ISSUE TITLE
Embedded installation - Studio not found

### ISSUE THREAD

**Issue by borekb** [ravendb/docs#104]
Regarding http://ravendb.net/docs/article-page/3.0/csharp/server/installation/embedded, when I follow the instructions and then visit localhost:8080, I get this error:

> { "Message": "The following embedded file was not available: index.html. Please make sure that the Raven.Studio.Html5.zip file exist in the main directory (near to the Raven.Database.dll)." }

The documentation is possibly incomplete.

**Comment by ayende** [comment]
How did you include the embedded? By using nuget or the zip file?

*Hibernating Rhinos Ltd  *

Oren Eini* l CEO l *Mobile: + 972-52-548-6969

Office: +972-4-622-7811 *l *Fax: +972-153-4-622-7811

**Comment by borekb** [comment]
NuGet (https://www.nuget.org/packages/RavenDB.Database/)

**Comment by mbp** [comment]
I have the same problem. With 2.5 we could visit studio when just using NuGet package. I think the index.html file should be part of the Embedded package.

**Comment by fitzchak** [comment]
http://issues.hibernatingrhinos.com/issue/RavenDB-3180

**Comment by fitzchak** [comment]
We will fix this, you can follow this issue:
http://issues.hibernatingrhinos.com/issue/RavenDB-3180

Best Regards,

*Hibernating Rhinos Ltd  *[image: cid:image001.png@01CF95E2.8ED1B7D0]

Fitzchak Yitzchaki l *Senior Software **Engineer* l Mobile:+972-58-345-9538
Office: +972-4-622-7811* l *Fax: +972-153-4-622-7811
