### ISSUE TITLE
Add docs for official python client?

### ISSUE THREAD

**Issue by kureus** [ravendb/docs#223]
The official python client seems to have hit version 1. Currently on 1.3 as of June 22nd (https://github.com/ravendb/RavenDB-Python-Client/releases/tag/1.3.0). Is there roadmap for when the official python client will be documented fully and included in the doc website? The documentation on the official python client repo readme is limited at best, for instance there is no example on how to update a document? 

Whats more that repo seems to have issues disabled for some reason so I can't even directly raise the update example issue or anything else and get the readme improved in the meantime?

**Comment by ayende** [comment]
Issue tracking for RavenDB isn't handled on a per repository basis, we track them all here: http://issues.hibernatingrhinos.com/

And yes, we'll document it fully.
You can track it here: 
http://issues.hibernatingrhinos.com/issue/RDoc-597
