### ISSUE TITLE
Data exploration view needs `where` sample

### ISSUE THREAD

**Issue by alexeyzimarev** [ravendb/docs#257]
I tried some valid LINQ queries with `where` over the collection but it always fails with query translation. There are no samples anywhere available. When I use `where true==true` it works so `where` is definitely supported but the syntax with using field values is either not there or not obvious.

**Comment by fitzchak** [comment]
Hello,

You should ask questions about RavenDB here:
https://groups.google.com/forum/#!forum/ravendb

And reporting issues should be done in our issue tracker:
http://issues.hibernatingrhinos.com/issues/RDoc#newissue=57-12373

**Comment by alexeyzimarev** [comment]
Why don’t you close the “issues” on this repo?

**Comment by fitzchak** [comment]
We will close it and update the readme with instructions where to open issues on RavenDB / Documentation and where to ask questions.
